//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Binary Parsing open source project
//
// Copyright (c) 2025 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
//
//===----------------------------------------------------------------------===//

@_lifetime(&input)
public func _loadAndCheckDirectBytes<
  T: FixedWidthInteger & MultiByteInteger & BitwiseCopyable
>(
  parsing input: inout ParserSpan,
  bigEndianValue: T
) throws(ParsingError) {
  let loadedValue = try T(parsingBigEndian: &input)
  guard loadedValue == bigEndianValue else {
    throw ParsingError(
      status: .invalidValue, location: input.startPosition)
  }
}

@_lifetime(&input)
public func _loadAndCheckDirectBytesByteOrder<
  T: FixedWidthInteger & MultiByteInteger & BitwiseCopyable
>(
  parsing input: inout ParserSpan,
  bigEndianValue: T
) throws(ParsingError) -> Endianness {
  let loadedValue = try T(parsingBigEndian: &input)
  if loadedValue == bigEndianValue {
    return .big
  } else if loadedValue.byteSwapped == bigEndianValue {
    return .little
  } else {
    throw ParsingError(
      status: .invalidValue,
      location: input.startPosition)
  }
}

/// Loads and validates bytes from a parser span against an expected InlineArray of bytes.
///
/// This function is used internally by the `#magic` macro to perform arbitrary-length
/// magic number validation using InlineArray for compile-time optimization.
///
/// The function:
/// 1. Parses exactly `N` bytes from the input span into an `InlineArray<N, UInt8>`
/// 2. Compares the parsed bytes against the expected bytes using InlineArray's Equatable conformance
/// 3. Throws a `ParsingError` with `.invalidValue` status if bytes don't match
/// 4. Consumes the bytes from the span regardless of whether comparison succeeds or fails
///
/// ## Usage
///
/// This function is primarily intended for use by macro-generated code:
/// ```swift
/// // Generated by #magic("test", parsing: &input)
/// try _loadAndCheckInlineArrayBytes(
///   parsing: &input,
///   expectedBytes: [116, 101, 115, 116]
/// )
/// ```
///
/// ## Availability
///
/// Requires macOS 26+, iOS 26+, watchOS 26+, tvOS 26+, visionOS 26+ due to `InlineArray` usage.
///
/// - Parameters:
///   - input: An inout `ParserSpan` to parse bytes from
///   - expectedBytes: An `InlineArray<N, UInt8>` containing the expected byte values
/// - Throws: `ParsingError` with `.invalidValue` status if bytes don't match, or propagates
///   any parsing errors from `InlineArray.init(parsing:)`
@available(macOS 26, iOS 26, watchOS 26, tvOS 26, visionOS 26, *)
@_lifetime(&input)
@inlinable
public func _loadAndCheckInlineArrayBytes<let N: Int>(
  parsing input: inout ParserSpan,
  expectedBytes: InlineArray<N, UInt8>
) throws(ParsingError) {
  let parsedBytes = try? InlineArray<N, UInt8>(parsing: &input)
  guard parsedBytes == expectedBytes else {
    throw ParsingError(
      status: .invalidValue, location: input.startPosition)
  }
}
